version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fullcycle
    networks:
      - db_node-net

  web:
    build: ./node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node src/index.js
    restart: always
    networks:
      - nginx_node-net
      - db_node-net
    depends_on:
      - db

  nginx:
    build: ./nginx
    entrypoint: dockerize -wait tcp://web:5000 -timeout 30s nginx -g "daemon off;"
    restart: always
    ports:
      - "8000:80"
    networks:
      - nginx_node-net
    depends_on:
      - web
    
networks:
  db_node-net:
    driver: bridge
  
  nginx_node-net:
    driver: bridge